#!/usr/bin/env zsh
COL_GOB_FORE=$COL_FORE'51;161;62m' #R;G;Bm
COL_GOB_BACK=$COL_BACK'77;34;110m' #R;G;Bm
COL_GOB=$COL_GOB_FORE$COL_GOB_BACK
COL_TERM_FORE=$COL_FORE'181;186;80'
COL_TERM_BACK=$COL_BACK'91;80;186m'
COL_TERM=$COL_TERM_FORE$COL_TERM_BACK
COL_PWD_FORE=$COL_FORE'19;100;186m' #R;G;Bm
COL_PWD_BACK=$COL_BACK'240;139;46m' #R;G;Bm
COL_PWD=$COL_PWD_FORE$COL_PWD_BACK
GOB_PROMPT=$(echo $COL_GOB'goblin-%m'$COL_CLEAR) #%m => hostname
GOB_TERM=$(echo $COL_TERM'\t%l'$COL_CLEAR)
PWD_PROMPT=$(echo $COL_PWD'\t%~'$COL_CLEAR) #%~ => PWD
PS1=$GOB_PROMPT$GOB_TERM$PWD_PROMPT$NEWLINE"%(?..$(echo -n "%{$COL_ERR%}")%? $(echo -n "%{$COL_CLEAR%}"))%# " #PS1 is weird and doesnt like newlines
