COL_GOB_FORE=$COL_FORE'51;161;62m' #R;G;Bm
COL_GOB_BACK=$COL_BACK'77;34;110m' #R;G;Bm
COL_GOB=$COL_GOB_FORE$COL_GOB_BACK
COL_PWD_FORE=$COL_FORE'19;100;186m' #R;G;Bm
COL_PWD_BACK=$COL_BACK'240;139;46m' #R;G;Bm
COL_PWD=$COL_PWD_FORE$COL_PWD_BACK
GOB_PROMPT=$(echo $COL_GOB'goblin-%m'$COL_CLEAR) #%m => hostname
PWD_PROMPT=$(echo $COL_PWD'\t%~'$COL_CLEAR) #%~ => PWD
PS1=$GOB_PROMPT$PWD_PROMPT$NEWLINE"%% " #PS1 is weird and doesnt like newlines
