#!/usr/bin/env bash

fatal() {
	echo "[FATAL]" $@
	exit 1
}

warn() {
	echo "[WARN]" $@
}

_main() {
	if [ -z $1 -o -z $2 ]; then
		fatal "Neither argument can be empty";
	fi
	if [ ! -e $1 ]; then
		warn "Target doesnt exist, creating empty file"
		mkdir -p `dirname $1`
		touch $1
	fi
	mkdir -pv `dirname $2`
	cp $1 $2
	rm $1
	ln -s `realpath $2` $1
	exit 0
}

_main $1 $2
