$horizontal = ~/wallpapers/horizontal.jpg
$vertical = ~/wallpapers/vertical.jpg
$fallback = ~/wallpapers/fallback.jpg
wallpaper {
	monitor = DP-1
	path = $horizontal
}
wallpaper {
	monitor = DP-2
	path = $vertical
}
wallpaper {
	monitor =
	path = $fallback
}
