#!/usr/bin/env bash

main() {
	local msg=$(cat $1 | head -n 1)

	[[ "${msg}" =~ ^[^()]+(\(.+\))?!?:' '.+ ]] || {
		echo "omg bruh" >&2
		echo "oh hell nah man, wtf man" >&2
		echo "who invited this kid" >&2
		echo "get yo ass home boy" >&2
		exit 1
	}
}

main $@
